sudo: required
services:
  - docker

before_install:
  - docker build -t francotagliero/docker-react -f Dockerfile.dev .

script:
  - docker run francotagliero/docker-react npm run test -- --coverage
